#+title: Chicken Tikka

* Ingrediants

180g Chicken thighs skinless boneless
150g red bell peppers
70g onions
2 cloves of garlic
2 pieces of ginger
400g canned crushed tomatoes
100g evaporated milk 3% fat
100g greek yogurt
1/4 tsp cumin
1/4 tsp chili powder
1/2 tsp turmeric
1/2 tsp paprika
Salt
1/2 lemon

* Instructions
First, cut the chicken thighs into big chunks and add them into a bowl. Mix in a glass cumin, paprika, turmeric, chili, and salt and mix. Add to the bowl with chicken the greek yogurt, half of the spice mix, grate in 1 clove of garlic and a piece of ginger, and the juice of the lemon. Mix everything and place it in the fridge for 30 minutes to 4 hours to marinate.

In the meantime chop up onions and the bell peppers and prepare all other ingredients.

In a pan on medium-high heat, add a bit of oil and fry the chicken pieces for 2 minutes each side until they are browned. Then remove them from the pan, add another bit of oil, and fry the onions and the peppers for 3-4 minutes under occasional stirring. Then grate in garlic and ginger add the other half of the spices and keep stirring for 30 seconds.

Now go in with the canned tomatoes and the evaporated milk and give everything a stir until the sauce turns orange. Now reduce the heat to medium-low, close the lid, and let it simmer for 12-15 minutes.

Serve it with a serving of rice (60g weighed raw) or 250g of boiled potatoes. Top with cilantro or parsley, done!
