#+title: Fish Piccata

* Link
https://lizapanelim.com/%D7%A4%D7%99%D7%A9-%D7%A4%D7%99%D7%A7%D7%90%D7%98%D7%94/
* Ingridiants
- 2-3 skinless white fish cut into quarters (sea bass, sea bream, locust mullet, etc.)
- 3/4 cup flour mixed with a teaspoon of salt and half a teaspoon of black pepper
- 2 beautiful fresh fennels cut into quarters
- 10 cherry tomatoes
- red onion cut into large cubes
- 3 tablespoons of olive oil
- teaspoon of coarse salt
- stalk of oregano
- peeled and boiled potato cut into slices
- 3/4 cup of white wine
- 3/4 cup of water
- 20 g of butter
- 4 tablespoons of olive oil
- juice of half a lemon

* Instructions
1. Heat the oven to grill mode, spread the fennel, tomatoes and onions on a baking sheet, pour 3 tablespoons of olive oil and coarse salt on them, mix lightly and put in the oven for about half an hour until caramelized and golden. Let it cool
2. We will slice a boiled potato
3. We will flour pieces of fish on both sides, in a flat pot with four spoons of olive oil we will arrange the floured pieces of fish, we will intersperse the fennel, onion, cherry tomatoes and potatoes, salt and pepper.
4. Pour 3/4 cup of white wine and 3/4 cup of water, when it bubbles, cover the pot on a small fire for about 15 minutes. Nakba.
5. Sprinkle a favorite herb on top such as: mint, coriander, parsley, oregano, tarragon, etc.
6. Crumble the butter into small drops and spread on the beds of fish and vegetables in the pot. We will melt on the hot stove gently.

** Optional
1. to replace fennel with:/capsules/asparagus/zucchini and even artichoke hearts
2. instead of flour you can use cornflour
3. does not replace the white wine, at all a good white wine, the kind you would drink.
4. Instead of butter, a little olive oil.

5. It is possible without potato
