#+title: Japanese Curry

* [[https://www.justonecookbook.com/simple-chicken-curry/][Link]]
[[https://www.justonecookbook.com/pressure-cooker-japanese-curry/][Pressure cooker version]]
* Ingrediants
** Optional depends on vibes
Unless stated otherwise, add with the broth and cook together
*** Sweet
- Chutneye
- Honey (add honey with broth and cook it, do not add after curry roux)
- Ketchup
- Mashed banana
- Mirin
- Orange/apricot jam
*** Refreshing sour taste
- Lemon (add right before serving)
- Tomato
- Yoghurt
*** Spicy taste
- Red chili pepper
- Black pepper
- Cayenne pepper
*** Fragrance
- Cumin
- Bay leaf
- Cinnamon
- Curry leaves
*** Umami and depth
- Butter (add with roux)
- Chocolate (add with roux)
- Garlic cloves (Add while sauteeing)
- Fresh ginger (Add while sauteeing)
- Instant coffee
- Milk (Add with roux)
- Oyster sauce
- Red wine
- Sake
- Soy sauce
- Tonkatsu sauce or Worcestershire Sauce
** Sample ingrediants
- 3 onions (large; 2¼ lb, 1,005 g)
- 1½ carrots (5 oz, 143 g)
- 3 Yukon gold potatoes (15 oz, 432 g)
- 2 cloves garlic
- 1 tsp ginger (grated, with juice)
- 1½ lb boneless, skinless chicken thighs
- ⅛ tsp Diamond Crystal kosher salt
- ⅛ tsp freshly ground black pepper
*** For the Curry Sauce
- 1 Tbsp neutral oil (for cooking)
- 3 cups chicken stock/broth (for lower sodium, use water only or half stock and half water)
- 1 package Japanese curry roux (7–8 oz or 200–230 g; or make my Japanese Curry Roux)
- 1 Tbsp ketchup
*** For Serving
- 6 servings cooked Japanese short-grain rice
- fukujinzuke (Japanese red pickled vegetables) (optional; or make my Homemade Fukujinzuke)
- 1 Tbsp soy sauce
* Instructions

** To prepare the ingredients

Cut 3 onions in half and cut each half into 5 wedges.

Peel 1½ carrots and cut into bite-sized pieces. I use a Japanese cutting technique called rangiri. This cut creates more surface area, which helps the carrots absorb more flavor and cook faster. Tip: You can cut the vegetables slightly bigger to avoid a mushy texture.

Peel 3 Yukon gold potatoes and cut them into quarters. Soak them in water for 15 minutes to remove the excess starch. Tip: Do not use russet potatoes since they would break down too easily.

Mince 2 cloves garlic (I like this garlic press). Then, grate the ginger with a microplane zester or ceramic grater and reserve 1 tsp ginger (grated, with juice).

Cut 1½ lb boneless, skinless chicken thighs into bite-sized pieces. I use the sogigiri Japanese cutting technique to create more surface area and flatten each piece so it cooks faster. Season with ⅛ tsp Diamond Crystal kosher salt and ⅛ tsp freshly ground black pepper.

** To Cook the Curry
Press the Sauté button on your Instant Pot (I use a 6 QT Instant Pot) or preheat a stovetop pressure cooker over medium heat. When the inner pot is hot, add 1 Tbsp neutral oil.

Then, add the onion wedges, minced garlic, and grated ginger with juice.

Add the chicken pieces to the pot and mix until just coated with the oil.

Add the carrots and potatoes to the pot and mix well.

Add 3 cups chicken stock/broth and use a spatula to press down the meat and vegetables into the liquid. Then, place the cubes from 1 package Japanese curry roux (I combine half mild and half medium spicy packaged roux) on top of the other ingredients. DO NOT MIX! Otherwise, the roux may sink to the bottom of the pot and burn while cooking. For solidified homemade roux, place the cubes on top of the ingredients and do not mix. For non-solidified homemade roux (that you just made), add it after pressure cooking is done.

Cover and lock the lid. Make sure the Instant Pot‘s steam release handle points to Sealing and not Venting. Press the Keep Warm/Cancel button on the Instant Pot to stop sautéing. Then, press the Meat/Stew button to switch to pressure cooking. Press the “minus“ button to change the cooking time to 15 minutes.

*For a Stovetop Pressure Cooker:* Close and lock the lid. Set the pressure level to high. Heat the pot on the stovetop over medium-high heat until you‘ve reached high pressure. Then, reduce the heat to medium low to maintain high pressure, and cook for 15 minutes.

When it is finished cooking, the Instant Pot will switch automatically to the Keep Warm mode. Slide the steam release handle to Venting to let out steam until the float valve drops down, OR let the pressure release naturally (this takes about 15 minutes).

Unlock the lid. (If you‘re using homemade curry roux, add it to the pot now and heat on Sauté mode for an additional 5 minutes until well blended into the stew.) Add 1 Tbsp ketchup and 1 Tbsp soy sauce now. Mix well, stirring to dissolve the curry roux and checking one last time that there are no undissolved chunks left. Tip: If you use my unsalted homemade curry roux, taste the curry sauce now and add salt to your liking. I recommend adding 2–4 tsp Diamond Crystal kosher salt, but this will vary based on the brand of the chicken broth and condiments you added.

** To Serve
Portion 6 servings cooked Japanese short-grain rice on individual plates and serve the curry on top. Serve with optional fukujinzuke (Japanese red pickled vegetables) on the side.


** To Store
Keep the leftovers in a glass airtight container and store it in the refrigerator for up to 3 days and in the freezer for a month. The texture of the potatoes will change in the freezer, so remove them before freezing. Defrost the frozen curry in the refrigerator for 24 hours before you want to reheat it.
To Reheat

Leftover curry sauce will thicken into a paste as it cools, so it tends to burn while reheating. To avoid this, stir ½ cup (120 ml) water or more into the leftover sauce until loosened. Then, gently reheat it on low heat. If the sauce seems thin, continue heating with the lid off to reduce the sauce.
