#+title: Mousakka

* Link
https://www.supergoldenbakes.com/a-lighter-moussaka/
* Ingrediants
** For meat sauce
- Live oil cooking spray
- 1 large white or red onion
- 3 garlic cloves , minced
- 750 g | 1lb 6.5oz extra lean beef mince
- 2 tbsp sweetener (Sukrin Gold)
- 2 tsp cinnamon
- 1 tsp salt
- Pinch ground cloves
- 1 tsp dried thyme
- 1 bay leaf
- 2 tbsp Worcestershire sauce
- 1 tbsp soy sauce or tamari
- 1 tsp fish sauce (optional)
- 100 g | 3 1/2 oz tomato paste (purée)
- 400 g | 14oz Passata (preferably passata rustica) or try Raphael's Sunshine Sauce
- 300 ml | 1 1/4 cups hot beef stock made with 2 stock cubes
** For eggplant layer
- 3 large aubergines (eggplants) or 4 smaller ones
- Olive oil cooking spray
- Salt
** For the topping
- 1 tbsp low fat spread
- 2 tbsp flour
- 450 g | 1 lb fat free Greek yogurt
- 200 g | 14oz Greek feta , crumbled (sub with fat free cottage cheese)
- 3 eggs , lightly beaten
- Salt and pepper
- Pinch freshly ground nutmeg
- 2 tbsp grated Parmesan (optional)
* Instructions
** Make the meat sauce
Lightly spray a pan or casserole with olive oil or low calorie cooking spray. Add the onions and garlic for cook over low heat, stirring, for five minutes.

Add the minced beef, breaking it up with the back of a wooden spoon. Brown the meat for a few minutes until nicely coloured.

Stir in the salt, sweetener (I used Sukrin Gold), thyme, cinnamon, cloves and bay leaf.

Add the tomato puree (paste), passata, soy, fish and Worcestershire sauces.

Stir in the beef stock and bring to a simmer. Cook over medium heat, stirring occasionally, for 30 minutes or until the sauce is thick and all the liquid has cooked down.

Discard the bay leaf. Taste the sauce and season with salt (if needed) and pepper.

Prepare the aubergine (eggplant)

While the meat sauce is bubbling away, slice the aubergine either widthways as I have done or in rounds. The slices need to be about 1 cm thick or a little thinner. Season with salt and spray with a little olive oil or low calorie cooking spray such as Fry light.

Pan fry the aubergine on a griddle pan for 3-4 minutes per side. Alternatively heat the grill (broiler) to high. Place the slices on a baking tray and cook for 8-10 minutes per side until soft – watch they don’t burn! Set the aubergine aside on paper towels while you make the topping.

** Make the topping
Heat the low calorie spread (such a s Flora Light) in a pan and then add the flour to make a paste (roux).

Stir in the Greek yoghurt and feta cheese. Mix until the sauce is well blended and smooth.

Take the pan off the heat and add the beaten eggs, mixing quickly so they don’t scrabble. Season well with salt, pepper and a pinch freshly grated nutmeg.

** Assemble the moussaka
Preheat the oven to 180C/350. Add a layer of meat sauce over an ovenproof baking dish (measuring at least 30x19cm /10 cup capacity) and pack it down.

Add a little of the sauce and layer with the aubergine slices.

Repeat with another layer of meat, a little sauce and more aubergine.

Top with the remaining cheese sauce and scatter with the grated Parmesan.

Bake for 45 minutes then leave the moussaka to rest for at least 15 minutes or longer.

Cut into slices and serve with a green salad on the side.
