#+title: Tomato Soup

* Link
https://allthehealthythings.com/whole30-tomato-basil-soup/
* Ingrediants
- 1 tablespoon OLIVE OIL
- 1 yellow onion, diced
- 3 cloves of garlic, minced
- 1/4 teaspoon crushed RED PEPPER FLAKES, plus more to taste
- 1 teaspoon SALT, plus more to taste
- 15oz can FIRE ROASTED TOMATOES
- 15oz can CRUSHED TOMATOES
- 1 cup CHICKEN BROTH
- 1/2 tablespoon BALSAMIC VINEGAR
- 1/2 cup chopped fresh basil, plus for more for serving
- 1/2 cup COCONUT MILK
* Instructions
Heat a dutch oven or heavy bottomed pot over medium heat. Once hot, add the olive oil, onion, and garlic. Sauté the onions and garlic for 4-5 minutes until the onions soften and become translucent.

Next, add the roasted diced tomatoes, crushed tomatoes, chicken broth, balsamic vinegar, salt, and red pepper flakes to the pot. Simmer the soup for 30 minutes.

After the soup has simmered, transfer it to a blender and blend until smooth. Then, add the fresh basil and blend again. Transfer the soup back to your pot and add in the coconut milk. Simmer for 10 more minutes.

Finish the soup with more fresh basil and enjoy!
